"""Bilibili / YouTube 下载引擎（基于 yt-dlp）。

抖音/TikTok 链接不经过本模块，仍走原有流程。
"""

from __future__ import annotations

import asyncio
import os
import re
import shutil
import sys
import time
from pathlib import Path
from typing import Any, Callable

from src.custom.internal import PROJECT_ROOT

__all__ = [
    "detect_platform",
    "extract_preview",
    "find_ffmpeg",
    "run_ytdlp_download",
    "save_platform_cookie",
]

_CACHE_DIR = PROJECT_ROOT.joinpath("cache")

_BILI_VIDEO = (
    r"^https?://(?:www\.|m\.)?bilibili\.com/video/(?:BV[\w]+|av\d+)",
    r"^https?://b23\.tv/",
    r"^https?://(?:www\.)?bilibili\.com/(?:festival|list)/",
)
_BILI_BATCH = (
    r"^https?://space\.bilibili\.com/\d+",
    r"^https?://(?:www\.)?bilibili\.com/lists/",
    r"^https?://(?:www\.)?bilibili\.com/channel/collectiondetail",
)
_YOUTUBE_VIDEO = (
    r"^https?://(?:www\.|m\.|music\.)?youtube\.com/(?:watch|shorts|live)",
    r"^https?://youtu\.be/[\w\-]+",
)
_YOUTUBE_BATCH = (
    r"^https?://(?:www\.)?youtube\.com/(?:channel|c)/",
    r"^https?://(?:www\.)?youtube\.com/@",
    r"^https?://(?:www\.)?youtube\.com/playlist\?",
)

_COOKIE_DOMAINS = {"bili": ".bilibili.com", "youtube": ".youtube.com"}
_COOKIE_LOGIN_KEYS = {
    "bili": ("SESSDATA",),
    "youtube": ("SID", "__Secure-1PSID", "SAPISID"),
}

_COOKIE_FILES: dict[str, Path] = {}


def detect_platform(url: str) -> tuple[str, str] | None:
    """返回 (平台, 类型)，类型为 video/batch；非目标平台返回 None。"""
    u = url.strip()
    for pattern in _BILI_BATCH:
        if re.match(pattern, u):
            return "bili", "batch"
    for pattern in _YOUTUBE_BATCH:
        if re.match(pattern, u):
            return "youtube", "batch"
    for pattern in _BILI_VIDEO:
        if re.match(pattern, u):
            return "bili", "video"
    for pattern in _YOUTUBE_VIDEO:
        if re.match(pattern, u):
            return "youtube", "video"
    return None


def _ffmpeg_search_dirs() -> list[Path]:
    candidates: list[Path] = []
    home = os.environ.get("DOUK_HOME")
    if home:
        candidates.append(Path(home))
    if getattr(sys, "frozen", False):
        exe_dir = Path(sys.executable).resolve().parent
        candidates.extend([exe_dir, exe_dir.parent])
    bundle = getattr(sys, "_MEIPASS", "")
    if bundle:
        candidates.append(Path(bundle))
    found = shutil.which("ffmpeg")
    if found:
        candidates.append(Path(found).parent)
    return candidates


def find_ffmpeg() -> str | None:
    """按 应用根目录(DOUK_HOME) → exe 目录 → exe 上级 → 打包目录(_internal) → PATH 顺序查找 ffmpeg。"""
    for c in _ffmpeg_search_dirs():
        if (c / "ffmpeg.exe").exists() or (c / "ffmpeg").exists():
            return str(c)
    return None


def save_platform_cookie(
    target: str,
    browser_name: str,
    parameter: Any,
    cookie_manager: Any,
) -> dict:
    """从浏览器读取指定平台 Cookie 并写入 Netscape 文件供 yt-dlp 使用。"""
    if target not in _COOKIE_DOMAINS:
        return {"success": False, "message": f"不支持的平台：{target}"}
    try:
        from src.tools import Browser

        browser = Browser(parameter, cookie_manager)
        cookie_dict = browser.get(
            browser_name, [_COOKIE_DOMAINS[target].lstrip(".")]
        )
    except Exception as e:
        return {"success": False, "message": f"读取浏览器 Cookie 失败：{e}"}
    if not cookie_dict:
        platform_name = "B站" if target == "bili" else "YouTube"
        return {
            "success": False,
            "message": f"未读取到 {platform_name} Cookie，请确认已在浏览器登录并关闭浏览器后重试",
        }
    _write_cookie_file(target, cookie_dict)
    logged_in = any(k in cookie_dict for k in _COOKIE_LOGIN_KEYS[target])
    return {"success": True, "count": len(cookie_dict), "logged_in": logged_in}


def _write_cookie_file(target: str, cookie_dict: dict[str, str]) -> Path:
    _CACHE_DIR.mkdir(parents=True, exist_ok=True)
    path = _cookie_path(target) or _CACHE_DIR.joinpath(
        f"ytdlp_cookies_{target}.txt"
    )
    expiry = int(time.time()) + 365 * 24 * 3600
    lines = ["# Netscape HTTP Cookie File", "# Generated by 抖音视频下载器"]
    for name, value in cookie_dict.items():
        lines.append(
            f"{_COOKIE_DOMAINS[target]}\tTRUE\t/\tTRUE\t{expiry}\t{name}\t{value}"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _COOKIE_FILES[target] = path
    return path


def _cookie_path(target: str) -> Path | None:
    """Cookie 文件解析：优先会话内路径，其次磁盘持久化文件（重启后仍有效）。"""
    path = _COOKIE_FILES.get(target) or _CACHE_DIR.joinpath(
        f"ytdlp_cookies_{target}.txt"
    )
    return path if path.exists() else None


def _is_bot_check(text: str) -> bool:
    markers = (
        "Sign in to confirm",
        "not a bot",
        "The page needs to be reloaded",
        "This content isn't available",
    )
    return any(m in text for m in markers)


_FALLBACK_CLIENTS = ("android_vr", "tv_simply", "web_embedded", "mweb", "tv")


def _client_opts(client: str | None) -> dict:
    if not client:
        return {}
    return {
        "extractor_args": {"youtube": {"player_client": [client]}}
    }


def _base_opts(logger_cb: Callable[[str], None]) -> dict:
    opts = {
        "quiet": True,
        "no_warnings": True,
        "noprogress": True,
        "socket_timeout": 30,
        "retries": 5,
        "logger": _YtdlpLogger(logger_cb),
        # yt-dlp 默认只启用 deno；显式开启全部运行时探测，
        # 否则机器上只有 node/bun 时无法解 YouTube 的 JS 挑战
        "js_runtimes": {"deno": {}, "node": {}, "bun": {}, "quickjs": {}},
    }
    return opts


class _YtdlpLogger:
    def __init__(self, cb: Callable[[str], None]):
        self._cb = cb

    def debug(self, msg: str) -> None:
        pass

    def info(self, msg: str) -> None:
        self._cb(str(msg))

    def warning(self, msg: str) -> None:
        self._cb(f"[警告] {msg}")

    def error(self, msg: str) -> None:
        self._cb(f"[错误] {msg}")


def _extract_sync(clean: str, flat: bool, platform: str, extra: dict) -> dict:
    from yt_dlp import YoutubeDL

    opts = _base_opts(lambda _: None)
    opts.update(
        {
            "skip_download": True,
            "noplaylist": not flat,
            "extract_flat": "in_playlist" if flat else False,
            # 预览阶段快速失败，避免网络不通时长时间等待
            "socket_timeout": 15,
            "retries": 1,
        }
    )
    cookie_file = _cookie_path(platform)
    if cookie_file:
        opts["cookiefile"] = str(cookie_file)
    opts.update(extra)
    with YoutubeDL(opts) as ydl:
        info = ydl.extract_info(clean, download=False)
    if info is None:
        raise RuntimeError("未能获取视频信息")
    return ydl.sanitize_info(info)


async def extract_preview(url: str, platform: str, kind: str) -> dict:
    """提取预览信息。单视频返回标题/UP主/封面/时长/清晰度列表；
    批量返回条目数与前若干个标题。"""
    clean = url.strip()
    flat = kind == "batch"
    try:
        info = await asyncio.to_thread(
            _extract_sync, clean, flat, platform, {}
        )
    except Exception as e:
        message = str(e)
        if platform == "youtube" and _is_bot_check(message):
            last = e
            for client in _FALLBACK_CLIENTS:
                try:
                    info = await asyncio.to_thread(
                        _extract_sync,
                        clean,
                        flat,
                        platform,
                        _client_opts(client),
                    )
                    break
                except Exception as e2:
                    last = e2
            else:
                raise RuntimeError(_friendly_error(last)) from last
        else:
            raise RuntimeError(_friendly_error(message)) from e

    result: dict = {"kind": kind}
    if flat:
        entries = list(info.get("entries") or [])
        result.update(
            {
                "title": info.get("title") or "",
                "uploader": info.get("uploader") or info.get("uploader_id") or "",
                "item_count": info.get("playlist_count") or len(entries) or None,
                "sample_titles": [
                    str(e.get("title") or e.get("id"))
                    for e in entries[:20]
                    if isinstance(e, dict)
                ],
            }
        )
        return result
    result.update(
        {
            "title": info.get("title") or "",
            "uploader": info.get("uploader") or "",
            "thumbnail": info.get("thumbnail") or "",
            "duration": info.get("duration"),
            "webpage_url": info.get("webpage_url") or clean,
            "formats": _norm_formats(info),
        }
    )
    return result


def _norm_formats(info: dict) -> list[dict]:
    best: dict[int, dict] = {}
    for f in info.get("formats") or []:
        if not isinstance(f, dict):
            continue
        height = f.get("height")
        if not height or f.get("vcodec") in (None, "none"):
            continue
        score = f.get("tbr") or 0
        kept = best.get(height)
        if kept is None or score > (kept.get("_score") or 0):
            best[height] = {
                "_score": score,
                "format_id": str(f.get("format_id") or ""),
                "label": f"{height}P"
                + ("60帧" if (f.get("fps") or 0) >= 50 else ""),
                "ext": f.get("ext") or "",
                "filesize": f.get("filesize")
                or f.get("filesize_approx"),
                "height": height,
                "_note": f.get("format_note") or "",
            }
    formats = sorted(best.values(), key=lambda x: x["height"], reverse=True)
    for f in formats:
        f.pop("_score", None)
    return formats


def _format_selector(fmt: str | None) -> tuple[str, str]:
    """返回 (yt-dlp format 选择器, 日志描述)。纯数字按高度上限处理。"""
    if not fmt:
        return "bestvideo*+bestaudio/best", "最高画质（自动合并最佳视频+音频）"
    if fmt.isdigit():
        h = int(fmt)
        return (
            f"bestvideo*[height<={h}]+bestaudio/best[height<={h}]/best",
            f"画质：不超过 {h}P",
        )
    return fmt, f"格式选择器：{fmt}"


async def run_ytdlp_download(
    task: dict,
    tasks_mgr: Any,
    url: str,
    root: Path,
    format_id: str | None = None,
) -> None:
    """执行下载任务，通过 tasks_mgr 记录日志与进度。"""
    from yt_dlp import YoutubeDL

    clean = url.strip()
    detection = detect_platform(clean)
    if detection is None:
        tasks_mgr.finish(task, False, "链接不是受支持的B站/YouTube格式")
        return
    platform, kind = detection
    platform_name = "B站" if platform == "bili" else "YouTube"

    def log(text: str) -> None:
        tasks_mgr.append_log(task, text)

    ffmpeg = find_ffmpeg()
    if not ffmpeg:
        searched = "、".join(str(c) for c in _ffmpeg_search_dirs())
        message = (
            f"未找到 ffmpeg（合并音视频必需）。已查找：{searched}。"
            "请把 ffmpeg.exe 放到以上任一目录后重试；"
            "若目录中确有 ffmpeg.exe 却仍报错，"
            "多半是被杀毒软件（360/Defender）隔离了，请恢复该文件或重新解压程序"
        )
        log(f"任务异常：{message}")
        tasks_mgr.finish(task, False, message)
        return

    def hook(d: dict) -> None:
        status = d.get("status")
        if status == "downloading":
            total = d.get("total_bytes") or d.get("total_bytes_estimate") or 0
            done = d.get("downloaded_bytes") or 0
            name = Path(d.get("filename") or "").name[:60]
            tasks_mgr.set_progress(task, done, total, message=name)
        elif status == "finished":
            log("文件下载完成，正在合并音视频…")

    def attempt(client: str | None) -> dict:
        selector, _ = _format_selector(format_id)
        opts = _base_opts(log)
        opts.update(
            {
                "format": selector,
                "outtmpl": str(
                    root.joinpath("%(title).100s [%(id)s].%(ext)s")
                ),
                "noplaylist": kind == "video",
                "ffmpeg_location": ffmpeg,
                "progress_hooks": [hook],
                "concurrent_fragment_downloads": 5,
            }
        )
        cookie_file = _cookie_path(platform)
        if cookie_file:
            opts["cookiefile"] = str(cookie_file)
            log(f"使用已导入的 {platform_name} Cookie")
        if client:
            log(f"尝试备用客户端 {client} 绕过风控…")
            opts.update(_client_opts(client))
        with YoutubeDL(opts) as ydl:
            info = ydl.extract_info(clean, download=True)
            if info is None:
                raise RuntimeError("下载失败：未返回结果信息")
        return info

    def work() -> None:
        try:
            info = attempt(None)
        except Exception as e:
            if platform == "youtube" and _is_bot_check(str(e)):
                last = e
                for client in _FALLBACK_CLIENTS:
                    try:
                        info = attempt(client)
                        break
                    except Exception as e2:
                        last = e2
                else:
                    raise last
            else:
                raise
        if kind == "batch":
            entries = info.get("entries")
            count = len(entries) if entries is not None else "?"
            log(f"批量处理完成，共 {count} 个条目")

    log(f"开始下载{platform_name}{'单视频' if kind == 'video' else '列表'}内容")
    log(f"保存目录：{root}")
    _, selector_note = _format_selector(format_id)
    log(f"画质策略：{selector_note}")
    try:
        await asyncio.to_thread(work)
        tasks_mgr.finish(task, True, "下载完成，可在保存目录查看文件")
    except Exception as e:
        message = _friendly_error(e)
        log(f"任务异常：{message}")
        tasks_mgr.finish(task, False, message)


def _friendly_error(e: Exception | str) -> str:
    text = str(e)
    if "ffmpeg" in text.lower():
        return text.split("ERROR:")[0].strip() or text
    if "Unsupported URL" in text:
        return "暂不支持该链接（yt-dlp 无法解析此地址）"
    if "Private video" in text or "members-only" in text:
        return "该内容为私有或会员专享，需要对应权限的 Cookie"
    login_wall = any(
        m in text
        for m in (
            "Sign in to confirm",
            "not a bot",
            "The page needs to be reloaded",
        )
    )
    if not login_wall and "This content isn't available" in text:
        return (
            "视频不可用或访问受限：可能已被删除、设为私享或存在地区限制，"
            "也可能是当前网络被 YouTube 风控，可更换网络后重试"
        )
    if login_wall or ("age" in text.lower() and "restrict" in text.lower()):
        if _cookie_path("youtube") is not None:
            return (
                "已导入 Cookie 但仍触发 YouTube 风控验证，"
                "通常是当前网络/代理 IP 被 YouTube 风控"
                "（Cookie 本身可能有效）。建议更换网络环境或代理节点后重试；"
                "Cookie 导入已久的话也可尝试重新导入"
            )
        return (
            "YouTube 风控验证：需要登录态。请点击右上角钥匙图标 →"
            "「一键导入全部 Cookie」或「导入YouTube Cookie」"
            "（导入前先完全关闭浏览器）后重试"
        )
    return text[:300]
